config/routes.rb
Distorrent::Application.routes.draw do
  resources :advanceds do
    collection do
  put :save
  end
  
  
  end

  resources :filterlists do
    collection do
  put :inc
  put :dec
  end
  
  
  end

  resources :rsslists
  match '/:controller(/:action(/:id))'
  match 'advanceds/save/' => 'advanced#save'
  match '/distorrent' => 'home#index'
  match '/' => 'home#index'
end


#								Vieille routes :
#
#ActionController::Routing::Routes.draw do |map|
#  map.resources :advanceds,  :collection => { :save => :put}
#
#  map.resources :filterlists, :collection => { :inc => :put, :dec =>:put}
#
#  map.resources :rsslists
#  map.connect ':controller/:action/:id'
#  map.connect ':controller/:action/:id.:format'
#  map.connect 'advanceds/save/',:controller =>"advanced",:action=>"save"
#  map.connect '/distorrent',:controller => "home",:action =>"index"
# # map.connect 'filterlists/inc/:id', {:controller => "filterlists", :action => "inc" }
# # map.connect 'filterlists/dec/:id', {:controller => "filterlists", :action => "dec" }
#  map.root :controller => "home"
#end

app/models/advanced.rb
class Advanced < ActiveRecord::Base
end

app/models/filterlist.rb
class Filterlist < ActiveRecord::Base
end

app/models/rsslist.rb
class Rsslist < ActiveRecord::Base
end

app/controllers/advanceds_controller.rb
class AdvancedsController < ApplicationController

  def save
    tpref=pref.symbolize_keys
    tpref[:pref]["cmd"]=params["cmd"]["f"]
    if params["logs"]
      tpref[:pref]["logs"]=1
    else
      tpref[:pref]["logs"]=nil
    end
    File.open( "#{Rails.root}/config/prefs.yml", 'w' ) do |out|
        YAML.dump(tpref, out)
    end
    @prefs=tpref[:pref]
    render 'index'
  end

  def index
    @prefs=pref.symbolize_keys[:pref]
    render 'index'
  end

end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details
  
  def pref
     raw_config = File.open("#{Rails.root}/config/prefs.yml")
     config = YAML.load(raw_config)
     #$prefs=config.symbolize_keys[:pref]
     config
   end
   

   


  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/filterlists_controller.rb
class FilterlistsController < ApplicationController

	def index
		@filterlists = Filterlist.all
		@prefs=pref.symbolize_keys[:pref]
		render :index
	end

	def show
		@filterlist = Filterlist.find(params[:id])
		@prefs=pref.symbolize_keys[:pref]
		render :show
	end

	def new
		@filterlist = Filterlist.new
		@prefs=pref.symbolize_keys[:pref]
	end

	def edit
		@filterlist = Filterlist.find(params[:id])
		@prefs=pref.symbolize_keys[:pref]
		render :edit
	end

	def create
		@filterlist = Filterlist.new(params[:filterlist])
		@prefs=pref.symbolize_keys[:pref]
		if @filterlist.save
			flash[:notice] = 'Filterlist was successfully created.'
			redirect_to(@filterlist)
		else
			render :new
		end
	end

	def update
		@filterlist = Filterlist.find(params[:id])
		@prefs=pref.symbolize_keys[:pref]
		if @filterlist.update_attributes(params[:filterlist])
			flash[:notice] = 'Filterlist was successfully updated.'
			redirect_to(@filterlist)
		else
			#render "edit" 
			render :edit
		end
	end


	def inc
		@filterlist = Filterlist.find(params[:id])
		@filterlist.update_attributes(:ep => @filterlist.ep+1)
		@filterlists = Filterlist.all
		@prefs=pref.symbolize_keys[:pref]
		render "index"
	end

	def dec
		@filterlist = Filterlist.find(params[:id])
		@filterlist.update_attributes(:ep => @filterlist.ep-1)
		@filterlists = Filterlist.all
		@prefs=pref.symbolize_keys[:pref]
		render "index"
	end


	def destroy
		@filterlist = Filterlist.find(params[:id])
		@filterlist.destroy
		@prefs=pref.symbolize_keys[:pref]
		flash[:notice] = 'Filter deleted.'
		redirect_to(@filterlist)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include Dl
	def scan
		@prefs=pref.symbolize_keys[:pref]
		@rss = Rsslist.all
		@nbrss = @rss.length
		@filter = Filterlist.all
		@result = []
		threads = []
		increm = []
		@rss.each {|a|   
			threads << Thread.new{ 
				begin
					#puts "begining to dl : #{a.adress.to_s}"
					Dl::down2(a.adress.to_s,"tmp/rss/#{a.id}.xml")	
				rescue
					puts $!
				else
					f=File.open("tmp/rss/#{a.id}.xml")
					unparse = Rssread.new(f)
					f.close				
					for z in 0..unparse.total-1 do								#parcour items du rss
						@filter.each do |afilter|								#parcour mes filtres
							@tempreg = "(#{afilter.regexp}[^1-9]*#{afilter.ep})"
							if /#{@tempreg}/xi.match(unparse.title[z]) then
								#puts unparse.link[z]
								lelien=unparse.link[z].gsub(/<!\[CDATA\[/,'').gsub(/\]\]>/,'').gsub(/&lt;/,'<').gsub(/&gt;/,'>').gsub(/&apos;/,'\'').gsub(/&quot;/,'"').gsub(/&amp;/,'&') #correction de l'url
								if lelien.include?("nyaa.eu")
									then
									lelien=lelien.gsub(/torrentinfo/,'download') #correction nyaa
								end
								unless (lelien=="no link") then
									nect = Dl::nectar2(lelien).gsub('/','').gsub(/torrent.*/,'torrent')
									#	puts "nect : #{nect}"
									if (/\.torrent/i.match("#{nect}")) then
										Dl::down2(lelien.to_s,"./tmp/torrents/#{nect}")
										#	puts "#{nect}"
										cmd=pref.symbolize_keys[:pref]["cmd"]
										if RUBY_PLATFORM =~ /mswin32/    then
											system("#{cmd} #{Rails.root}/tmp/torrents/#{nect}")
										else
											system("#{cmd} './tmp/torrents/#{nect}'")
										end
										lgg=Loggy.new
										lgg.push(afilter.name+'  '+afilter.ep.to_s)
										increm.push([afilter.id,afilter.ep])
										@result.push("#{afilter.name} #{afilter.ep}")
									end				
								else
									puts "gros arg : #{unparse.link[z]}"
								end
							end
						end
					end
				#	puts "#{a.adress.to_s} computed"
				end
			}
		} 
		threads.each { |aThread|  aThread.join }
		increm.uniq.each{|a| Filterlist.find(a[0]).update_attribute('ep', a[1]+1) }
	end
	def index
		@prefs=pref.symbolize_keys[:pref]
		@truc = Rsslist.all
	end
end

app/controllers/rsslists_controller.rb
class RsslistsController < ApplicationController
  # GET /rsslists
  # GET /rsslists.xml
  def index
    @rsslists = Rsslist.all
    @prefs=pref.symbolize_keys[:pref]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rsslists }
    end
  end

  # GET /rsslists/1
  # GET /rsslists/1.xml
  def show
    @rsslist = Rsslist.find(params[:id])
    @prefs=pref.symbolize_keys[:pref]
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rsslist }
    end
  end

  # GET /rsslists/new
  # GET /rsslists/new.xml
  def new
    @rsslist = Rsslist.new
    @prefs=pref.symbolize_keys[:pref]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rsslist }
    end
  end

  # GET /rsslists/1/edit
  def edit
    @rsslist = Rsslist.find(params[:id])
    @prefs=pref.symbolize_keys[:pref]
  end

  # POST /rsslists
  # POST /rsslists.xml
  def create
    @rsslist = Rsslist.new(params[:rsslist])
    @prefs=pref.symbolize_keys[:pref]
    respond_to do |format|
      if @rsslist.save
        flash[:notice] = 'Rsslist was successfully created.'
        format.html { redirect_to(@rsslist) }
        format.xml  { render :xml => @rsslist, :status => :created, :location => @rsslist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rsslist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rsslists/1
  # PUT /rsslists/1.xml
  def update
    @rsslist = Rsslist.find(params[:id])
    @prefs=pref.symbolize_keys[:pref]
    respond_to do |format|
      if @rsslist.update_attributes(params[:rsslist])
        flash[:notice] = 'Rsslist was successfully updated.'
        format.html { redirect_to(@rsslist) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rsslist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rsslists/1
  # DELETE /rsslists/1.xml
  def destroy
    @rsslist = Rsslist.find(params[:id])
    @rsslist.destroy
    @prefs=pref.symbolize_keys[:pref]
    respond_to do |format|
      format.html { redirect_to(rsslists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/advanceds_helper.rb
module AdvancedsHelper
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filterlists_helper.rb
module FilterlistsHelper
 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rsslists_helper.rb
module RsslistsHelper
end

app/views/advanceds/index.html.erb
<%= form_tag(:controller => "Advanceds", :action => "save", :method => "get") do %>
  <p>
    <%= label_tag("cmd", "Command :") %>
    <%= text_field "cmd","f",:value=>@prefs["cmd"] %>
  </p>
  <p>
	<%= label_tag("cmd", "Logs display :") %>
    <%= check_box_tag "logs","c",@prefs["logs"] %>
  </p>
  <p>
    <%= submit_tag("Save") %>
  </p>
<% end %>

app/views/filterlists/edit.html.erb
<%= form_for(@filterlist) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :regexp %><br />
    <%= f.text_field :regexp %>
  </p>
  <p>
    <%= f.label :ep %><br />
    <%= f.text_field :ep %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @filterlist , :class=> 'special' %> 
<%= link_to 'Back', filterlists_path , :class=> 'special' %>

app/views/filterlists/inc.html.erb
Increased !
<p>
	<div class='simple'>
		<b>Name:</b>
		<%=h @filterlist.name %>
	</div>
</p>

<p>
	<div class='simple'>
		<b>Regexp:</b>
		<%=h @filterlist.regexp %>
	</div>
</p>

<p>
	<div class='simple'>
		<b>Ep:</b>
		<%=h @filterlist.ep %>
	</div>
</p>
<p></p>
<br/>

<%= link_to 'Edit', edit_filterlist_path(@filterlist) , :class=> 'special' %> 
<%= link_to 'Destroy', @filterlist, :confirm => 'Are you sure?', :method => :delete , :class=>"special" %>
<%= link_to 'Back', filterlists_path , :class=> 'special' %>

app/views/filterlists/index.html.erb
<% @filterlists.each do |filterlist| %>
<div class='filter'>
    <div class="thename">  <%=h filterlist.name %> <%=h filterlist.ep %>
			<%=  link_to  filterlist.regexp, filterlist, :class =>"theadress"   %>
	</div>
	<%= link_to '+', filterlists_path+"/inc/"+filterlist.id.to_s , :class=>"incdec" %>
	<%= link_to '-', filterlists_path+"/dec/"+filterlist.id.to_s  , :class=>"incdec" %>
</div>
	<p></p>
<% end %>


<br />

<%= link_to 'New filterlist', new_filterlist_path,  :class=>"special"  %>

app/views/filterlists/new.html.erb
<%= form_for(@filterlist) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :regexp %><br />
    <%= f.text_field :regexp %>
  </p>
  <p>
    <%= f.label :ep %><br />
    <%= f.text_field :ep %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', filterlists_path , :class=> 'special' %>

app/views/filterlists/show.html.erb
<p>
	<div class='simple'>
		<b>Name:</b>
		<%=h @filterlist.name %>
	</div>
</p>

<p>
	<div class='simple'>
		<b>Regexp:</b>
		<%=h @filterlist.regexp %>
	</div>
</p>

<p>
	<div class='simple'>
		<b>Ep:</b>
		<%=h @filterlist.ep %>
	</div>
</p>
<p></p>
<br/>

<%= link_to 'Edit', edit_filterlist_path(@filterlist) , :class=> 'special' %> 
<%= link_to 'Destroy', @filterlist, :confirm => 'Are you sure?', :method => :delete , :class=>"special" %>
<%= link_to 'Back', filterlists_path , :class=> 'special' %>

app/views/home/index.html.erb
<h1>Welcome !</h1>
<p class='simple'>Thank's for using me !</p>

app/views/home/scan.html.erb
<div class='simple'>
	<b>scan effectué :
		<%=h @nbrss %> rss.
	</b>
</div>
<% @result.each {|b| %>
<p><%=h b %></p>
<% } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="fr">
<head>
   <meta charset="utf-8">
   <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
  <title>THOR <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'style' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
<div id="lapage">

	<header>
	<div id="logo">
		<img src='/images/thor.png' alt='Thor' />
	</div>
		<nav>
			<ul>	
				<li><%= link_to 'RSS',rsslists_path , :class => controller_name=='rsslists' %></li>
				<li><%= link_to 'Filters', filterlists_path, :class => controller_name=='filterlists'  %></li>
				<li><%= link_to 'Scan', {:controller => "home" , :action => "scan" }, :class => controller_name=='home' %></li>
				<li><%= link_to 'Advanced' ,{:controller => "advanceds",:action => "index"} , :class => controller_name=='advanceds' %></li>
			</ul>	
		</nav>
	</header>
	<section>
		<p style="color: green"><%= flash[:notice] %></p>
		<%= yield %>

	<footer>
		<div class= <%= "e"+ @prefs['logs'].to_s %> >
			<% Loggy.new.lastdls.each do |l| %>	
			<p>
				<%= l %>
			</p>
			<% end %>
		</div>
		<p class='shinyfooter'> Contain some Alban Avenant inside </p>	
	</footer>

</div>
</body>
</html>

app/views/rsslists/edit.html.erb
<%= form_for(@rsslist) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :adress %><br />
    <%= f.text_field :adress %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @rsslist , :class=> 'special' %> 
<%= link_to 'Back', rsslists_path , :class=> 'special' %>

app/views/rsslists/index.html.erb
<% @rsslists.each do |rsslist| %>
		<div class="thename">  <%=h rsslist.name %>
			<%=  link_to  rsslist.adress, rsslist, :class =>"theadress"   %>
		</div>
		<p></p>
<% end %>

<br/> 
<%= link_to 'New rsslist', new_rsslist_path, :class=>"special" %>

app/views/rsslists/new.html.erb
<%= form_for(@rsslist) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :adress %><br />
    <%= f.text_field :adress %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', rsslists_path , :class=> 'special' %>

app/views/rsslists/show.html.erb
<p>
	<div class='simple'>
  		<b>Name:</b>
 		<%=h @rsslist.name %>
 	</div>
</p>

<p>
	<div class='simple'>
		<b>Adress:</b>
		<%=h @rsslist.adress %>
	</div>
</p>
<p></p>
<br/>


<%= link_to 'Edit', edit_rsslist_path(@rsslist) , :class=> 'special' %>
<%= link_to 'Destroy', @rsslist, :confirm => 'Are you sure?', :method => :delete , :class=>"special" %>
<%= link_to 'Back', rsslists_path , :class=> 'special' %>